# Generated by Django 4.2.11 on 2024-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='branch',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Biotechnology Engineering', 'Biotechnology Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=41),
        ),
    ]
