# Generated by Django 5.0.4 on 2024-04-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_requests_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='dob',
            field=models.DateField(default=0.0004992511233150275),
            preserve_default=False,
        ),
    ]
